#!/bin/env python3


import os
import subprocess
import sys
import re

imgur_hold = []
page_count = 1
page_max = 954


while page_count <= page_max:
    if page_count > 1 and page_count < page_max + 1:
        page = "/page-"
        count = page_count
    elif page_count == 1:
        page = "/"
        count = ""
    else:
        print("We're All Done Here")
        sys.exit(0)
    page_count = page_count + 1
    bass_thread = "https://www.avsforum.com/threads/the-ultimate-list-of-bass-in-movies-w-frequency-charts.2763785" + page + str(count) + " | grep -i imgur | grep url"
    img_finder = subprocess.Popen('curl -s ' + bass_thread, shell=True, stdout=subprocess.PIPE)
    for imgfind in img_finder.stdout:
        imgfind = imgfind.decode()
        imgfind = imgfind.rstrip()
        imgfind = re.findall(r'data-url=\"(.*)\" alt*=',imgfind)
        for ifind in imgfind:            
            imgfnd = ifind.split(" ")
            print(bass_thread)
            print(imgfnd[0]) 


'''
bass_thread = "https://www.avsforum.com/threads/the-ultimate-list-of-bass-in-movies-w-frequency-charts.2763785" + page + str(count) + " | grep -i imgur | grep url"
curl -s https://www.avsforum.com/threads/the-ultimate-list-of-bass-in-movies-w-frequency-charts.2763785/ | grep -i imgur
'''
