#!/usr/local/bin/env python3 

import sys
from time import sleep


fib_counter = 0
count = 1
fib_list = []
while True:
    fib_list.append(fib_counter)
    print(fib_counter)
    fib_counter = fib_counter + count
    count = count + fib_counter
    sleep(.5)