- hosts: localhost
  gather_facts: False
  vars_files: ./share_vars.yml
  tasks:
    - name: Build Credentials for role assumption
      sts_assume_role:
        role_arn: "arn:aws:iam::{{share_id}}:role/Corp2Dev"
        role_session_name: "Corp2Dev"
      register: assumed_role

     - debug:
          var: assumed_role


    - name: Set Variables for Later Use
      set_fact:
        ssm{{index+1}}: "{{ lookup('aws_ssm', '/ci/res_ami_{{item}}_hardened_id') }}"
      loop: "{{app}}"
      loop_control:
        index_var: index

    - name: Promote AMI from Corp to New Environment
      ec2_ami:
        image_id: "{{ lookup('aws_ssm', '/ci/res_ami_{{item}}_hardened_id') }}"
        state: present
        launch_permissions:
          user_ids: ["{{share_id}}"]
      loop: "{{ app }}"

    
    - name: Apply AMI IDs into SSM Parameter Store
      aws_ssm_parameter_store:
        aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
        aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
        security_token: "{{ assumed_role.sts_creds.session_token }}"
        name: "/ci/res_ami_{{item|lower}}_hardened_id"
        description: "The AMI ID for {{item|upper}}"
        value: "ssm{{index+1}}"
      loop: "{{app}}"
      loop_control:
        index_var: index


 
