#!/bin/bash

export AWS_ACCESS_KEY_ID="{{aws_access_key}}"
export AWS_SECRET_ACCESS_KEY="{{aws_secret_key}}"
export AWS_DEFAULT_REGION="{{region}}"

echo $AWS_ACCESS_KEY_ID
echo $AWS_SECRET_ACCESS_KEY
exit 0

echo "Adding Rules to {{sgid}}"
aws ec2 authorize-security-group-ingress --group-id {{sgid}} --ip-permissions IpProtocol=tcp,FromPort=0,ToPort=65535,IpRanges=[{CidrIp=0.0.0.0/0}]


echo "$VPCID is the VPC ID we're working with"
sleep 0.5
echo "Building CIDR Associations with VPC"

for x in 10.6.0.0/16 10.7.0.0/16
do
  echo "Adding $x to $VPCID"
  aws ec2 associate-vpc-cidr-block --vpc-id $VPCID --cidr-block $x
done
