 - sts_assume_role:
    role_arn: "{{rolearn}}"
    role_session_name: "{{rolename}}"
   register: assumed_role

 - set_fact:
     new_ec2: "{{item}}"
   with_lines: cat ./fm_instance_ip_address1

 - set_fact:
     ansible_pass: "{{ lookup('aws_secret', '/privami/userpass', aws_access_key=assumed_role.sts_creds.access_key, aws_secret_key=assumed_role.sts_creds.secret_key, aws_security_token=assumed_role.sts_creds.session_token) }}"

 - debug:
     var: new_ec2

 - add_host:
     hostname: "{{new_ec2}}"
     ansible_user: Administrator
     ansible_password: "{{ansible_pass}}"
     ansible_connection: winrm
     ansible_winrm_transport: ntlm
     ansible_winrm_server_cert_validation: ignore

 - name: Install AWS CLI Tools for Powershell
   win_command: "powershell Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force; Install-Module -Name AWSPowerShell -Force; Install-Module -Name AWSPowerShell.NetCore -AllowClobber -Force"
   args:
     chdir: c:\
   delegate_to: "{{new_ec2}}"

 - name: Copy Files To Host
   win_copy: 
     remote_src: no
     src: "{{item}}"
     dest: c:\temp\
   with_items:
     - "files/chrome_install.ps1"
     - "files/ad_join.ps1"
   delegate_to: "{{new_ec2}}"

 - name: Run Powershell Scripts
   win_command: "{{item}}"
   args:
     chdir: c:\temp\
   loop:
     - "powershell c:\\temp\\chrome_install.ps1"
     - "powershell c:\\temp\\ad_join.ps1"
   delegate_to: "{{new_ec2}}"

