#!/usr/bin/env python3

import os
import sys
import re
import boto3
import subprocess
import time
import datetime

current_date = datetime.datetime.now()
currdate = current_date.strftime("%Y-%m-%d")
currdate_split = currdate.split('-')

'''
roleArnList = []

'''

roleArnList = []

for rA in roleArnList:
    roleArn = rA
    print("Operating under Role ARN: " + roleArn)
    roleSessionName = 'AdminRole'
    sts = boto3.client('sts')
    assumeRole = sts.assume_role(RoleArn=roleArn, RoleSessionName=roleSessionName)
    access_key = assumeRole['Credentials']['AccessKeyId']
    secret_key = assumeRole['Credentials']['SecretAccessKey']
    session_token = assumeRole['Credentials']['SessionToken']
    accountName = re.findall('.*-(.*)', roleArn)
    for aN in accountName:
        aN = aN
    ec2 = boto3.client('ec2', aws_access_key_id=access_key, aws_secret_access_key=secret_key, aws_session_token=session_token)
    sts = boto3.client('sts', aws_access_key_id=access_key, aws_secret_access_key=secret_key, aws_session_token=session_token)
    AccountInfo = sts.get_caller_identity()
    AccountID = AccountInfo['Account']
    #csvout = open(aN.upper() + '_Deleted_Snapshots.csv', 'a')
    #csvout.write('Account ID,Snapshot ID,Snapshot Created,Age (In Days),Description\n')
    describe_volumes = ec2.describe_volumes()
    for dv in describe_volumes['Volumes']:
        volumeId = dv['VolumeId']
        describe_volume_status = ec2.describe_volume_status(VolumeIds=[volumeId])
        print(describe_volume_status)
        print("\n\n\n\n")
        for dvs in describe_volume_status['VolumeStatuses']:
            print(dvs)
        sys.exit(0)
        '''
        starttime = ds['StartTime']
        starttime = starttime.strftime("%Y-%m-%d")
        snapshotId = ds['SnapshotId']
        description = ds['Description']
        owner = ds['OwnerId']
        starttime_split = starttime.split('-')
        try:
            start_date = datetime.datetime(year=int(starttime_split[0]), month=int(starttime_split[1]), day=int(starttime_split[2]))
            now_date = datetime.datetime(year=int(currdate_split[0]), month=int(currdate_split[1]), day=int(currdate_split[2]))
            date_delta = now_date - start_date
            days_old = date_delta.days
            if days_old > 364:
                days_old = str(days_old)
                print("Deleting " + snapshotId + " in " + str(AccountID) + " as it is " + days_old + " days old.")
                #delete_snapshot = ec2.delete_snapshot(SnapshotId=snapshotId)
                #print(delete_snapshot)
                #csvout.write(AccountID + "-" + aN + "," + snapshotId + "," + str(starttime) + "," + days_old + "," + description + "\n")
        except:
            pass
    #csvout.close()
    '''