Description: res-llc.com Route53 Zone and DNS records
Parameters:
  DefaultTTL:
    Type: Number
    Description: Default lifetime for DNS records
    Default: 3600
Resources:
  resllc:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub   res-llc   -    see CFN stack '${AWS::StackName}'
      Name: res-llc.com.
  Root:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: res-llc
      HostedZoneId: !Ref resllc
      Name: res-llc.com.
      ResourceRecords:
      - 184.175.188.229
      TTL: !Ref DefaultTTL
      Type: A
  Auth:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: res-llc
      HostedZoneId: !Ref resllc
      Name: auth.res-llc.com.
      ResourceRecords:
      - 184.175.188.236
      TTL: !Ref DefaultTTL
      Type: A
  CRM:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: res-llc
      HostedZoneId: !Ref resllc
      Name: crm.res-llc.com.
      ResourceRecords:
      - 184.175.188.236
      TTL: !Ref DefaultTTL
      Type: A
  DEV:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: res-llc
      HostedZoneId: !Ref resllc
      Name: dev.res-llc.com.
      ResourceRecords:
      - 184.175.188.236
      TTL: !Ref DefaultTTL
      Type: A
  GS:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: res-llc
      HostedZoneId: !Ref resllc
      Name: dev.res-llc.com.
      ResourceRecords:
      - 184.175.188.236
      TTL: !Ref DefaultTTL
      Type: A
  MailRecord1:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: MailRecord1
      HostedZoneId: !Ref resllc
      Name: res-llc.com.
      ResourceRecords:
      - 5 alt2.aspmx.l.google.com.
      - 1 aspmx.l.google.com.
      - 10 alt4.aspmx.l.google.com
      - 5 alt1.aspmx.l.google.com
      - 10 alt3.aspmx.l.google.com
      TTL: !Ref DefaultTTL
      Type: MX
  MS:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: MS
      HostedZoneId: !Ref resllc
      Name: res-llc.com.
      ResourceRecords:
      - '"MS=ms42649692"'
      - '"google-site-verification=P7mmBBgGqOeY9QOpxUJ7MiZ8YKONl8tROt4hKgeRLwM"'
      TTL: !Ref DefaultTTL
      Type: TXT
  DMARC:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: MS
      HostedZoneId: !Ref resllc
      Name: _dmarc.res-llc.com.
      ResourceRecords:
      - '"v=DMARC1; p=none; rua=mailto:vpaaxg37@ag.dmarcian.com, mailto:ACole@dentalhero.com"'
      TTL: !Ref DefaultTTL
      Type: TXT
  DKIM:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: MS
      HostedZoneId: !Ref resllc
      Name: google._domainkey.res-llc.com.
      ResourceRecords:
      - '"v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCKqngx9AlKHvdMtfs68E28cfTdD8MulxjTo5aEm6DyfpnGa2o/tIe7mdkUmobiqucPKEawhbmcpgN2orSBlUsdz45mi8Z/Q0sSOEIyhx0Ba3qOg5jDJSHcDkAlwZiU/Ntv6im/eu5r5TCLwrUSJG0lYkz15A98FcSUrXmN+7M7EQIDAQAB"'
      TTL: !Ref DefaultTTL
      Type: TXT
  SPF:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: MS
      HostedZoneId: !Ref resllc
      Name: res-llc.com.
      ResourceRecords:
      - '"v=spf1 include:_spf.google.com include:_spf.sendergen.com ~all"'
      TTL: !Ref DefaultTTL
      Type: SPF
  SipFederationTLS:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: SipFederationTLS
      HostedZoneId: !Ref resllc
      Name: _sipfederationtls._tcp.res-llc.com.
      ResourceRecords:
      - 100 1 5061 sipfed.online.lync.com.
      TTL: !Ref DefaultTTL
      Type: SRV
  SipTLS:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: SipTLS
      HostedZoneId: !Ref resllc
      Name: _sip._tls.res-llc.com.
      ResourceRecords:
      - 100 1 443 sipdir.online.lync.com.
      TTL: !Ref DefaultTTL
      Type: SRV
  Autodiscover:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: Autodiscover
      HostedZoneId: !Ref resllc
      Name: autodiscover.res-llc.com.
      ResourceRecords:
      - mail.r-mail.com.
      TTL: !Ref DefaultTTL
      Type: CNAME
  Lyncdiscover:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: Lyncdiscover
      HostedZoneId: !Ref resllc
      Name: lyncdiscover.res-llc.com.
      ResourceRecords:
      - webdir.online.lync.com.
      TTL: !Ref DefaultTTL
      Type: CNAME
  SIP:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: SIP
      HostedZoneId: !Ref resllc
      Name: sip.res-llc.com.
      ResourceRecords:
      - sipdir.online.lync.com.
      TTL: !Ref DefaultTTL
      Type: CNAME
  Smart:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: Smart
      HostedZoneId: !Ref resllc
      Name: smart.res-llc.com.
      ResourceRecords:
      - whs.sendergen.com.
      TTL: !Ref DefaultTTL
      Type: CNAME
#@                       A	184.175.188.229
#@                       MX	1	aspmx.l.google.com.
#@                       MX	5	alt1.aspmx.l.google.com.
#@                       MX	5	alt2.aspmx.l.google.com.
#@                       MX	10	alt4.aspmx.l.google.com.
#@                       MX	10	alt3.aspmx.l.google.com.
#@                       TXT	( "v=spf1 include:_spf.google.com include:_spf.sendergen.com ~all" )
#@                       TXT	( "google-site-verification=P7mmBBgGqOeY9QOpxUJ7MiZ8YKONl8tROt4hKgeRLwM" )
#@                       TXT	( "MS=ms42649692" )
#_dmarc                  TXT	( "v=DMARC1; p=none; rua=mailto:vpaaxg37@ag.dmarcian.com, mailto:ACole@dentalhero.com" )
#google._domainkey       TXT	( "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCKqngx9AlKHvdMtfs68E28cfTdD8MulxjTo5aEm6DyfpnGa2o/tIe7mdkUmobiqucPKEawhbmcpgN2orSBlUsdz45mi8Z/Q0sSOEIyhx0Ba3qOg5jDJSHcDkAlwZiU/Ntv6im/eu5r5TCLwrUSJG0lYkz15A98FcSUrXmN+7M7EQIDAQAB" )
#_sipfederationtls._tcp  SRV	100 1 5061	sipfed.online.lync.com.
#_sip._tls               SRV	100 1 443	sipdir.online.lync.com.
#auth                    A	184.175.188.236
#autodiscover            CNAME	mail.r-mail.com.
#crm                     A	184.175.188.236
#dev                     A	184.175.188.236
#lyncdiscover            CNAME	webdir.online.lync.com.
#sip                     CNAME	sipdir.online.lync.com.
#smart                   CNAME	whs.sendergen.com.
#
#;
#;  Delegated sub-zone:  smtp.res-llc.com.
#;
#smtp                    NS	gslb1.nsdirector.com.
#gslb1.nsdirector.com.   A	184.175.188.239
#gslb1.nsdirector.com.   A	172.16.26.21
#smtp                    NS	gslb2.nsdirector.com.
#gslb2.nsdirector.com.   A	67.98.30.108
#gslb2.nsdirector.com.   A	172.17.26.21
#;  End delegation
#
#sts                     A	184.175.188.236
#updates                 A	184.175.188.234
#www                     A	184.175.188.229