Description: tesiapartnerportal.com Route53 Zone and DNS records
Parameters:
  DefaultTTL:
    Type: Number
    Description: Default lifetime for DNS records
    Default: 3600
Resources:
  tesiapartnerportal:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Sub tesiapartnerportal - see CFN stack '${AWS::StackName}'
      Name: tesiapartnerportal.com.
  Root:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: tesiapartnerportal
      HostedZoneId: !Ref tesiapartnerportal
      Name: tesiapartnerportal.com.
      ResourceRecords:
      - 184.175.158.7
      TTL: !Ref DefaultTTL
      Type: A
  WWW:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: WWW
      HostedZoneId: !Ref tesiapartnerportal
      Name: www.tesiapartnerportal.com.
      ResourceRecords:
      - tesiapartnerportalpartnerportal.com.
      TTL: !Ref DefaultTTL
      Type: CNAME
  SPF:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: SPF
      HostedZoneId: !Ref tesiapartnerportal
      Name: tesiapartnerportal.com.
      ResourceRecords:
      - '"v=spf1 mx ip4:67.98.30.113 ip4:184.175.188.240 -all"'
      TTL: !Ref DefaultTTL
      Type: SPF

#@                       A	184.175.158.7
#@                       TXT	 "v=spf1 mx ip4:67.98.30.113 ip4:184.175.188.240 -all" 
#test                    A	184.175.158.7
#www                     CNAME	tesiapartnerportalpartnerportal.com.